"""Migrating models

Revision ID: cd41cc25b558
Revises: 6c282a51a22a
Create Date: 2025-07-16 16:26:17.904787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd41cc25b558'
down_revision = '6c282a51a22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
